from typing import List, Optional, Literal
from pydantic import BaseModel, Field
from enum import Enum

class ConversationMessage(BaseModel):
    role: Literal["user", "assistant", "system"]
    content: str
    timestamp: Optional[str] = None

class CustomerIntent(str, Enum):
    AUTHORIZED = "AUTHORIZED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CONFUSED = "CONFUSED"
    CONTRADICTION = "CONTRADICTION"
    UNCERTAIN = "UNCERTAIN"
    UNKNOWN = "UNKNOWN"

class ConversationState(BaseModel):
    """Tracks the structured state of the conversation with the customer."""
    customer_intent: CustomerIntent = Field(default=CustomerIntent.UNKNOWN, description="The detected intent of the customer.")
    confirmation_attempts: int = Field(default=0, description="Number of times the agent has tried to confirm the transaction.")
    missing_information_resolved: bool = Field(default=False, description="True if the customer has provided any missing information requested.")
    contradiction_detected: bool = Field(default=False, description="True if the customer gives conflicting answers.")

class ConversationAction(BaseModel):
    """Generated by Conversation Orchestrator to update state and respond."""
    action_type: Literal["Explain", "AskQuestion", "Recommend", "Escalate", "End"]
    message_to_customer: str = Field(..., description="The exact message to send to the customer. MUST use actual transaction values (e.g. ₹85000, Coinbase). NEVER use placeholders like [insert amount].")
    internal_notes: Optional[str] = Field(None, description="Notes for the system or auditor.")
    requires_response: bool = Field(False, description="True if the agent is expecting an answer from the customer.")
    updated_state: ConversationState = Field(..., description="The parsed conversation state based on the customer's input.")
