from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class DecisionResult(BaseModel):
    """Generated by the deterministic Decision Resolution Engine."""
    decision: Literal["APPROVE_TRANSACTION", "BLOCK_TRANSACTION", "CANCEL_TRANSACTION", "ESCALATE_TO_HUMAN", "REQUEST_MORE_INFORMATION"] = Field(..., description="The final automated decision.")
    reason: str = Field(..., description="The deterministic rule that triggered this decision.")
    confidence: float = Field(..., description="The confidence score of the decision (0.0 to 1.0).")
    recommended_actions: List[str] = Field(default_factory=list, description="Actions to be executed by the Action Executor.")
    workflow_completed: bool = Field(..., description="True if the transaction workflow has reached a terminal state.")
    requires_human_escalation: bool = Field(..., description="True if a human agent must review the case.")
