from typing import List, Optional
from pydantic import BaseModel, Field

class Evidence(BaseModel):
    feature: str = Field(..., description="The feature or attribute (e.g., 'Recipient', 'Time of day')")
    explanation: str = Field(..., description="Human-readable explanation of why this feature is risky or safe.")
    impact: str = Field(..., description="Positive, Negative, or Neutral impact on the risk score.")
    confidence: float = Field(..., description="Confidence score for this specific piece of evidence (0-1).")

class EvidenceReport(BaseModel):
    """Generated by Risk Interpretation Agent."""
    transaction_id: str
    overall_summary: str = Field(..., description="A 1-2 sentence summary of the risk assessment.")
    primary_risk_factors: List[Evidence] = Field(..., description="List of the most important risk factors.")
    mitigating_factors: List[Evidence] = Field(..., description="List of factors that reduce the risk.")
    scam_typology: Optional[str] = Field(None, description="The identified scam pattern, if any (e.g., 'Investment Scam').")
