from typing import List, Optional, Dict
from pydantic import BaseModel, Field

class PolicyRule(BaseModel):
    rule_id: str
    description: str
    action_required: str

class PolicyDecision(BaseModel):
    """Generated by Policy & Compliance Agent."""
    is_compliant: bool = Field(..., description="Whether the transaction passes all baseline compliance checks.")
    requires_human_approval: bool = Field(..., description="Whether the transaction must be paused for human confirmation.")
    action: str = Field(..., description="The recommended action: e.g., 'Approve', 'Reject', 'Require Customer Confirmation', 'Delay'")
    triggered_rules: List[PolicyRule] = Field(default_factory=list, description="Specific business rules triggered by this context.")
    rationale: str = Field(..., description="Explanation of why this policy decision was made.")
    recommendations: List[str] = Field(default_factory=list, description="Prioritized contextual recommendations (e.g., 'Cancel Transaction', 'Block Recipient').")
    confidence_scores: Dict[str, float] = Field(
        default_factory=dict, 
        description="Confidence metrics (0.0 to 1.0) for 'Overall Confidence', 'Decision Confidence', 'Memory Confidence', 'Recommendation Confidence'"
    )
    confidence_explanation: Optional[str] = Field(None, description="Explanation of why these confidence scores were produced.")

