"""enrich_behavior_profile

Revision ID: 77e94b4da1b2
Revises: 04ec85f71176
Create Date: 2026-07-03 20:11:23.726039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e94b4da1b2'
down_revision: Union[str, Sequence[str], None] = '04ec85f71176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_profiles', sa.Column('transaction_count', sa.Integer(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('average_daily_transactions', sa.Float(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('preferred_transfer_hour', sa.Integer(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('trusted_recipients', sa.JSON(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('known_devices', sa.JSON(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('known_locations', sa.JSON(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('average_balance', sa.Float(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('last_transaction', sa.DateTime(timezone=True), nullable=True))
    op.add_column('behavior_profiles', sa.Column('historical_risk', sa.Float(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('trust_score', sa.Integer(), nullable=True))
    op.add_column('behavior_profiles', sa.Column('trust_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behavior_profiles', 'trust_level')
    op.drop_column('behavior_profiles', 'trust_score')
    op.drop_column('behavior_profiles', 'historical_risk')
    op.drop_column('behavior_profiles', 'last_transaction')
    op.drop_column('behavior_profiles', 'average_balance')
    op.drop_column('behavior_profiles', 'known_locations')
    op.drop_column('behavior_profiles', 'known_devices')
    op.drop_column('behavior_profiles', 'trusted_recipients')
    op.drop_column('behavior_profiles', 'preferred_transfer_hour')
    op.drop_column('behavior_profiles', 'average_daily_transactions')
    op.drop_column('behavior_profiles', 'transaction_count')
    # ### end Alembic commands ###
